### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mrchvz** [Maxvien/next-shopify-storefront#43]
Hi, I'm trying to install this repo, but haven't had luck. The node version I'm trying to use is 14.15.4.
Which node version are you using?
Can you please upload the package-lock.json? 

Asking because I'm unsure that my versions match your versions.

Thanks :)

**Comment by VienDinhCom** [comment]
Hi @mrchvz 

I released version v2 here: https://github.com/maxvien/next-shopify-storefront/tree/v2

I hope it could solve your problems.
