### ISSUE TITLE
Support for collections

### ISSUE THREAD

**Issue by MohamedBassem** [Maxvien/next-shopify-storefront#56]
Hi 👋

Thanks a lot for building such an amazing project. Saved me a lot of time. I'm wondering if you're interested in adding support for collections. I've implemented it in my own fork, and if you're interested, I'd be happy to port it back to this repo.

The way I implemented it is by adding another button in the toolbar beside the `Products` button, called `Collections`. Clicking on that button, you'll get a paginated list of collections (in the same card format of product, just without a price). When you click on any of the collections, you'll get the list of products inside this collection (reusing the product list page).

Let me know if you're interested.

**Comment by VienDinhCom** [comment]
That's great! Just create an PR to see how it goes! Thank @MohamedBassem!
